project:
  type: website
  output-dir: docs
website:
  back-to-top-navigation: false
  sidebar:
    style: "docked"
    background: "#BEBEDF"
    search: true
    contents:
      - section: "Chapitres"
        contents:
          - index.qmd
          - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    backgroundcolor: "lavender"

editor: visual
lang: fr

